# Site settings
course_name: CIS5370 Computer Security
course_description: "We will cover a range of materials on computer security including software security, hardware security, web security and AI security."
course_semester: "Fall 2025"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cis5370-fall2025.github.io/" # the base hostname & protocol for your site

schoolname: "Florida State University"
schoolurl: "https://www.cs.fsu.edu"
twitter_username: FSUComputerSci

address: |
    Department of Computer Science
    Florida State University
    Tallahassee, Florida

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
